name: Node Continous Integration

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs_on: windows-server-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm init
      - run: npm start
